# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  buildConfiguration: 'Release'

jobs:
- job: Linux_Build_and_Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET sdk 6.0'
    inputs:
      version: 6.x
  - script: dotnet build -c $(buildConfiguration) -v n
    displayName: 'dotnet build'
  - script: dotnet test -c $(buildConfiguration) -f net6.0
    displayName: 'dotnet test'

- job: MacOS_Build_and_Test
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET sdk 6.0'
    inputs:
      version: 6.x
  - script: dotnet build -c $(buildConfiguration) -v n
    displayName: 'dotnet build'
  - script: dotnet test -c $(buildConfiguration) -f net6.0
    displayName: 'dotnet test'

- job: Windows_Build_and_Test
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET sdk 6.0'
    inputs:
      version: 6.x
  - script: dotnet build -c $(buildConfiguration) -v n
    displayName: 'dotnet build'
  - script: dotnet test -c $(buildConfiguration) -f net6.0
    displayName: 'dotnet test'
